### ISSUE TITLE
Bad contrast between chosen colors.

### ISSUE THREAD

**Issue by jipehome** [netmackan/ATimeTracker#118] opened 2019-02-04 14:58 UTC
**Describe the bug**
I just got an update of this software. (Version 0.51).
Someone has apparantly decided to change some color scheme.
The main parts of the application now goes in white.
The problem is that the color of text in at least two places is light grey and yellow.
The yellow especially is unreadable on my device (Huawei P10, standard software, recently upgraded).

**To Reproduce**
- Skipped

**Expected behavior**
Readable text.

**Actual behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Huawei P10
Android 8.0.0

**Additional context**

**Comment by netmackan** [comment] 2019-02-06 18:11
There are no intended color changes as far as I know.

Did you get the app from F-Droid or Google Play?

**Comment by richman490** [comment] 2019-02-06 18:36
Same issue here. Updated from google play

moto g6
Android 8.0.0

**Comment by jipehome** [comment] 2019-02-06 18:39
Google play. Automatic update.
Tnx


Den ons 6 feb. 2019 19:11Markus <notifications@github.com> skrev:

**Comment by avh4** [comment] 2019-02-07 06:38
I upgraded via F-Droid, and also see that now the app has a white background when in previous versions it had a black background.

LG Nexus 5
Android 7.1.2

**Comment by avh4** [comment] 2019-02-07 06:53
I don't see anything obvious in the code changes between https://github.com/netmackan/ATimeTracker/compare/v0.50...v0.51, though I do note that compileSdkVersion changed from 14 to 26...

In the [notes for SDK version 26](https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#O), there's the following:

> Some compatibility code in Resources that attempts to use the default Theme the app may be using will be turned off, requiring the app to explicitly request resources with the right theme.

I wonder if that might have anything to do with the color change?

**Comment by ds33** [comment] 2019-02-07 15:36
I updated from FDroid and am also seeing the background change from black to white. The contrast for the checkmark by the selected task is poor, but the bigger contrast issue for me is in the "Report" function where the columns now alternate between white and dark gray. The dark gray columns have black text that is basically unreadable. Since I use the "Report" function for my billable time at work this is a real problem for me.

Thanks for a great app and your work on it though.

**Comment by netmackan** [comment] 2019-02-07 18:34
Hmm, I uninstalled my own build and then installed the officiall F-Droid build but I am still unable to reproduce the problem. However, I have an older device and maybe there is something changed i later Android versions(?). Maybe colors are not handled correctly and it becomes an issue first on newer devices... :s

Android: 6.0.1, no problem

**Comment by netmackan** [comment] 2019-02-07 18:38
I think the note on SDK version 26 from @avh4 could potentially be the issue.

**Comment by jipehome** [comment] 2019-02-07 18:49
It's ages since I did something on Android but what about emulation. Do you have one with 8.0.0?

**Comment by realrufans** [comment] 2019-02-08 04:03
This should be similar if not what the OP is referring to. I'm on Android 0

![Screenshot_20190208-050212.png](https://cdn.steemitimages.com/DQmb2fjKvYg9FancXWCwtRrAhX6yuxjkHzsMAMXsKwMruye/Screenshot_20190208-050212.png)

**Comment by majkaz** [comment] 2019-02-08 12:37
I have the same colors as mentioned, including the yellow from the last post.

My system:
MIUI 10, Android version 7.0, phone Redmi Note Global 4X

**Comment by netmackan** [comment] 2019-02-09 13:55
I was able to reproduce this issue also on an older device by explicitly specifying the 'Light' theme. I was then able to fix it by changing the specified theme to a dark one so I believe this should be fixed with commit  
729859b.

**Comment by netmackan** [comment] 2019-02-09 14:13
A beta version with this change is published on the testing channel of Google Play if anyone could try it out and let us know if it works or not:
https://play.google.com/apps/testing/com.markuspage.android.atimetracker

**Comment by realrufans** [comment] 2019-02-09 14:20
Works.. but what happens to those that don't like dark themes?


# Solution
I suggest the best thing to do is changing the tech color instead of changing background color from light to Holo.

Let the text color be the one that will fit both  light & Holo background.

There should also be an option to change themes

**Comment by majkaz** [comment] 2019-02-09 14:28
Just confirming - the beta works for me too.

**Comment by netmackan** [comment] 2019-02-09 14:38
The app was always dark previously so the main bug was that it unintendently changed to light background when the API level was updated and thus did not play well with the text colors.

So for this bug I am thinking this ticket could be closed and the 0.51.1 version published so there will be a working version out. Thank you @realrufans and @majkaz for testing it!

I also like the idea from @realrufans and others to address the light gray and yellow colors and possibly if it makes sense to have a theme change option (?) but I consider that less urgent so it could be a separate ticket for 0.52 or later.

**Comment by netmackan** [comment] 2019-02-09 15:04
To be released with 0.51.1.

**Closed by netmackan** 2019-02-09 15:04 UTC
Labels: bug

**Comment by jipehome** [comment] 2019-02-09 22:21
Great, thanks for your work and swift response! I like this app due to it's simplicity.
